using Discord;

public static class OverwritePermissionsUtility
{
    public readonly static OverwritePermissions InheritAllPermissions = new OverwritePermissions();
    public readonly static OverwritePermissions AllowAllPermissions =
        new OverwritePermissions(
            manageChannel: PermValue.Allow,
            addReactions: PermValue.Allow,
            viewChannel: PermValue.Allow,
            sendMessages: PermValue.Allow,
            sendTTSMessages: PermValue.Allow,
            manageMessages: PermValue.Allow,
            embedLinks: PermValue.Allow,
            attachFiles: PermValue.Allow,
            readMessageHistory: PermValue.Allow,
            mentionEveryone: PermValue.Allow,
            useExternalEmojis: PermValue.Allow,
            connect: PermValue.Allow,
            speak: PermValue.Allow,
            muteMembers: PermValue.Allow,
            deafenMembers: PermValue.Allow,
            moveMembers: PermValue.Allow,
            useVoiceActivation: PermValue.Allow,
            manageRoles: PermValue.Allow,
            manageWebhooks: PermValue.Allow,
            prioritySpeaker: PermValue.Allow,
            stream: PermValue.Allow,
            useSlashCommands: PermValue.Allow,
            useApplicationCommands: PermValue.Allow,
            requestToSpeak: PermValue.Allow,
            manageThreads: PermValue.Allow,
            createPublicThreads: PermValue.Allow,
            createPrivateThreads: PermValue.Allow,
            usePublicThreads: PermValue.Allow,
            usePrivateThreads: PermValue.Allow,
            useExternalStickers: PermValue.Allow,
            sendMessagesInThreads: PermValue.Allow,
            startEmbeddedActivities: PermValue.Allow
        );
    public readonly static OverwritePermissions DenyAllPermissions =
        new OverwritePermissions(
            manageChannel: PermValue.Deny,
            addReactions: PermValue.Deny,
            viewChannel: PermValue.Deny,
            sendMessages: PermValue.Deny,
            sendTTSMessages: PermValue.Deny,
            manageMessages: PermValue.Deny,
            embedLinks: PermValue.Deny,
            attachFiles: PermValue.Deny,
            readMessageHistory: PermValue.Deny,
            mentionEveryone: PermValue.Deny,
            useExternalEmojis: PermValue.Deny,
            connect: PermValue.Deny,
            speak: PermValue.Deny,
            muteMembers: PermValue.Deny,
            deafenMembers: PermValue.Deny,
            moveMembers: PermValue.Deny,
            useVoiceActivation: PermValue.Deny,
            manageRoles: PermValue.Deny,
            manageWebhooks: PermValue.Deny,
            prioritySpeaker: PermValue.Deny,
            stream: PermValue.Deny,
            useSlashCommands: PermValue.Deny,
            useApplicationCommands: PermValue.Deny,
            requestToSpeak: PermValue.Deny,
            manageThreads: PermValue.Deny,
            createPublicThreads: PermValue.Deny,
            createPrivateThreads: PermValue.Deny,
            usePublicThreads: PermValue.Deny,
            usePrivateThreads: PermValue.Deny,
            useExternalStickers: PermValue.Deny,
            sendMessagesInThreads: PermValue.Deny,
            startEmbeddedActivities: PermValue.Deny
        );

    public readonly static OverwritePermissions ReadOnlyPermissions =
        new OverwritePermissions(
            manageChannel: PermValue.Deny,
            addReactions: PermValue.Deny,
            viewChannel: PermValue.Allow,
            sendMessages: PermValue.Deny,
            sendTTSMessages: PermValue.Deny,
            manageMessages: PermValue.Deny,
            embedLinks: PermValue.Deny,
            attachFiles: PermValue.Deny,
            readMessageHistory: PermValue.Allow,
            mentionEveryone: PermValue.Deny,
            useExternalEmojis: PermValue.Deny,
            connect: PermValue.Deny,
            speak: PermValue.Deny,
            muteMembers: PermValue.Deny,
            deafenMembers: PermValue.Deny,
            moveMembers: PermValue.Deny,
            useVoiceActivation: PermValue.Deny,
            manageRoles: PermValue.Deny,
            manageWebhooks: PermValue.Deny,
            prioritySpeaker: PermValue.Deny,
            stream: PermValue.Deny,
            useSlashCommands: PermValue.Deny,
            useApplicationCommands: PermValue.Deny,
            requestToSpeak: PermValue.Deny,
            manageThreads: PermValue.Deny,
            createPublicThreads: PermValue.Deny,
            createPrivateThreads: PermValue.Deny,
            usePublicThreads: PermValue.Deny,
            usePrivateThreads: PermValue.Deny,
            useExternalStickers: PermValue.Deny,
            sendMessagesInThreads: PermValue.Deny,
            startEmbeddedActivities: PermValue.Deny
        );
}
